# Generated by Django 4.2.5 on 2023-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allactivity",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
