# Generated by Django 4.2.5 on 2023-09-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("slots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_appointment",
                to="appointments.genericappointment",
            ),
        ),
    ]
