# Generated by Django 4.2.5 on 2023-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time_zone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
