# Generated by Django 4.2.5 on 2023-09-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Complain", "Complain"),
                            ("Therapy", "Therapy"),
                            ("Just talk", "Just talk"),
                        ],
                        default="Therapy",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                (
                    "appointment_medium",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Video Call", "Video Call"),
                            ("Voice Call", "Voice Call"),
                            ("Text Message", "Text Message"),
                            ("Walk in", "Walk in"),
                        ],
                        default="Walk in",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("re_scheduled", models.BooleanField(default=False)),
                (
                    "amount_to_pay",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "actual_price",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "actual_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("review", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Created", "Created"),
                            ("Pending", "Pending"),
                            ("Rescheduled", "Rescheduled"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                            ("Started", "Started"),
                            ("Ongoing", "Ongoing"),
                            ("Review", "Review"),
                            ("Completed", "Completed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Pending",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("appointment_start", models.DateTimeField(blank=True, null=True)),
                ("appointment_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "human_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_hr",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
