# Generated by Django 4.2.5 on 2023-09-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericappointment",
            name="appointment_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericappointment",
            name="appointment_cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericappointment",
            name="appointment_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericappointment",
            name="appointment_declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericappointment",
            name="appointment_rescheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
