# Generated by Django 4.2.5 on 2023-09-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_genericappointment_appointment_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericappointment",
            name="appointment_completed_at",
        ),
    ]
