# Generated by Django 4.2.5 on 2023-09-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_clients", models.BooleanField(default=False)),
                ("view_client_detail", models.BooleanField(default=False)),
                ("create_client", models.BooleanField(default=False)),
                ("edit_client", models.BooleanField(default=False)),
                ("delete_client", models.BooleanField(default=False)),
                ("view_calender", models.BooleanField(default=False)),
                ("set_availability", models.BooleanField(default=False)),
                ("time_off", models.BooleanField(default=False)),
                ("create_appointment", models.BooleanField(default=False)),
                ("edit_appointment", models.BooleanField(default=False)),
                ("delete_appointment", models.BooleanField(default=False)),
                ("edit_profile", models.BooleanField(default=False)),
                ("sms_notification", models.BooleanField(default=False)),
                ("email_notification", models.BooleanField(default=False)),
                ("push_notification", models.BooleanField(default=False)),
                ("view_earnings", models.BooleanField(default=False)),
                ("payment_history", models.BooleanField(default=False)),
                ("report_access", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practitioner_privilege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumanResourcesPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_client", models.BooleanField(default=False)),
                ("remove_client", models.BooleanField(default=False)),
                ("book_client", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_privilege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_practitioners", models.BooleanField(default=False)),
                ("book_appointment", models.BooleanField(default=False)),
                ("edit_profile", models.BooleanField(default=False)),
                ("view_history", models.BooleanField(default=False)),
                ("change_status", models.BooleanField(default=False)),
                ("can_cancel", models.BooleanField(default=False)),
                ("can_reschedule", models.BooleanField(default=False)),
                ("payment_history", models.BooleanField(default=False)),
                ("make_payment", models.BooleanField(default=False)),
                ("access_invoice", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_privilege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointerPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_clients", models.BooleanField(default=False)),
                ("view_client_detail", models.BooleanField(default=False)),
                ("create_client", models.BooleanField(default=False)),
                ("edit_client", models.BooleanField(default=False)),
                ("delete_client", models.BooleanField(default=False)),
                ("view_calender", models.BooleanField(default=False)),
                ("set_availability", models.BooleanField(default=False)),
                ("time_off", models.BooleanField(default=False)),
                ("create_appointment", models.BooleanField(default=False)),
                ("edit_appointment", models.BooleanField(default=False)),
                ("delete_appointment", models.BooleanField(default=False)),
                ("edit_profile", models.BooleanField(default=False)),
                ("sms_notification", models.BooleanField(default=False)),
                ("email_notification", models.BooleanField(default=False)),
                ("push_notification", models.BooleanField(default=False)),
                ("view_earnings", models.BooleanField(default=False)),
                ("payment_history", models.BooleanField(default=False)),
                ("report_access", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointer_privilege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointeePrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_practitioners", models.BooleanField(default=False)),
                ("book_appointment", models.BooleanField(default=False)),
                ("edit_profile", models.BooleanField(default=False)),
                ("view_history", models.BooleanField(default=False)),
                ("change_status", models.BooleanField(default=False)),
                ("can_cancel", models.BooleanField(default=False)),
                ("can_reschedule", models.BooleanField(default=False)),
                ("payment_history", models.BooleanField(default=False)),
                ("make_payment", models.BooleanField(default=False)),
                ("access_invoice", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointee_privilege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_user", models.BooleanField(default=False)),
                ("edit_user", models.BooleanField(default=False)),
                ("delete_user", models.BooleanField(default=False)),
                ("create_practitioner", models.BooleanField(default=False)),
                ("edit_practitioner", models.BooleanField(default=False)),
                ("delete_practitioner", models.BooleanField(default=False)),
                ("view_appointments", models.BooleanField(default=False)),
                ("create_appointments", models.BooleanField(default=False)),
                ("modify_appointments", models.BooleanField(default=False)),
                ("cancel_appointments", models.BooleanField(default=False)),
                ("access_calender", models.BooleanField(default=False)),
                ("modify_calender", models.BooleanField(default=False)),
                ("generate_reports", models.BooleanField(default=False)),
                ("view_transactions", models.BooleanField(default=False)),
                ("modify_transaction_status", models.BooleanField(default=False)),
                ("email_notification_settings", models.BooleanField(default=False)),
                ("customer_support", models.BooleanField(default=False)),
                ("logs_access", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_privilege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
